import type { GuideSetOption, GuideTemplate, StatKey } from "@/lib/types";

const four = (aliases: string[]): GuideSetOption => ({ pieces: 4, aliases });
const two = (aliases: string[]): GuideSetOption => ({ pieces: 2, aliases });

const CRIT: StatKey[] = ["cr", "cd"];

function dps(
  partial: Omit<GuideTemplate, "sands" | "goblet" | "circlet" | "scaling"> & {
    sands?: StatKey[];
    goblet?: StatKey[];
    circlet?: StatKey[];
    scaling?: GuideTemplate["scaling"];
  }
): GuideTemplate {
  return {
    ...partial,
    scaling: partial.scaling ?? "atk",
    sands: partial.sands ?? ["atk_"],
    goblet: partial.goblet ?? ["atk_"],
    circlet: partial.circlet ?? CRIT,
  };
}

export const LOCAL_GUIDES: Record<number, GuideTemplate> = {
  10000046: dps({
    id: 10000046,
    role: "메인 딜러",
    scaling: "hp",
    sands: ["hp_", "em"],
    goblet: ["pyro", "hp_"],
    circlet: CRIT,
    sets: [four(["불타오르는", "crimson", "witch", "화염의 마녀"]), four(["시메나", "shimenawa", "추억"])],
    setNote: "마녀 4셋, 또는 시메나와 4셋.",
    substats: "치명타 → 생명력% → 원소 마스터리 → 원소 충전",
    erMin: 120,
    erNote: "원소폭발을 자주 쓰면 130% 근처까지 올려도 됩니다.",
    talentFocus: "normal",
    talentNote: "평타를 먼저 올리고, 그다음 원소폭발.",
    weaponNote: "생명력·치명타 피해 무기(호마, 호두 전용 무기)가 맞습니다. 공격력% 무기는 효율이 떨어집니다.",
    teamNote: "증발 조합. 행추·야란으로 물을 붙이고, 실드가 있으면 평타를 안정적으로 넣습니다.",
  }),
  10000060: dps({
    id: 10000060,
    role: "서브 딜러",
    scaling: "hp",
    sands: ["hp_", "er"],
    goblet: ["hydro", "hp_"],
    circlet: CRIT,
    sets: [four(["절연", "emblem", "severed"])],
    setNote: "절연 4셋.",
    substats: "원소 충전 → 생명력% → 치명타",
    erMin: 180,
    erNote: "단독 배터리면 200% 전후. 라이덴·파보가 있으면 160%대도 됩니다.",
    talentFocus: "burst",
    talentNote: "원소폭발을 10레벨 근처까지.",
    weaponNote: "원소 충전 또는 생명력 활. 재련보다 충전 확보가 먼저입니다.",
    teamNote: "호두·요이미야·나비아 쪽에 물을 붙이는 서브 딜러.",
  }),
  10000052: dps({
    id: 10000052,
    role: "서브 딜러",
    sands: ["er", "atk_"],
    goblet: ["electro", "atk_"],
    circlet: CRIT,
    sets: [four(["절연", "emblem", "severed"])],
    setNote: "절연 4셋.",
    substats: "원소 충전(200% 이상) → 치명타 → 공격력%",
    erMin: 220,
    erNote: "원소폭발 게이지가 90이라 220~270%가 목표입니다.",
    talentFocus: "burst",
    talentNote: "원소폭발이 본체. 원소전투는 그다음.",
    weaponNote: "충전 창(참봉, 어획)이 기본. 공격력 창은 충전이 넘칠 때.",
    teamNote: "국가 파티(향릉·행추·베넷)의 배터리이자 딜러.",
  }),
  10000023: dps({
    id: 10000023,
    role: "서브 딜러",
    sands: ["er", "atk_", "em"],
    goblet: ["pyro"],
    circlet: CRIT,
    sets: [four(["절연", "emblem", "severed"]), four(["불타오르는", "crimson", "witch", "마녀"])],
    setNote: "절연 4셋. 증발이면 마녀 4셋도 됩니다.",
    substats: "원소 충전 → 치명타 → 원소 마스터리",
    erMin: 180,
    erNote: "베넷·라이덴이 있으면 160%대, 없으면 200%를 봅니다.",
    talentFocus: "burst",
    talentNote: "원소폭발만 올려도 제 역할을 합니다. 평타는 올리지 않아도 됩니다.",
    weaponNote: "충전 창(어획, 결투의 창)이 우선입니다.",
    teamNote: "국가, 또는 베넷과 함께 불을 켜 주는 서브 딜러.",
  }),
  10000025: dps({
    id: 10000025,
    role: "서브 딜러",
    sands: ["atk_", "er"],
    goblet: ["hydro", "atk_"],
    circlet: CRIT,
    sets: [four(["절연", "emblem", "severed"]), four(["옛 왕실", "noblesse"])],
    setNote: "절연 4셋.",
    substats: "원소 충전 → 공격력% → 치명타",
    erMin: 180,
    erNote: "희생검이면 150% 근처, 아니면 200%를 목표로.",
    talentFocus: "burst",
    talentNote: "원소폭발 위주. 원소전투는 그다음.",
    weaponNote: "희생검이 가장 편합니다. 없으면 충전 검.",
    teamNote: "호두·다이루크·나비아에게 물을 붙입니다.",
  }),
  10000032: dps({
    id: 10000032,
    role: "서포터",
    sands: ["er", "hp_"],
    goblet: ["hp_", "pyro"],
    circlet: ["heal", "hp_", "cr"],
    sets: [four(["옛 왕실", "noblesse"])],
    setNote: "왕실 4셋.",
    substats: "원소 충전 → 생명력",
    erMin: 200,
    erNote: "원소폭발을 돌릴 때마다 쓰려면 200~220%.",
    talentFocus: "burst",
    talentNote: "원소폭발의 공격력 버프만 보면 됩니다.",
    weaponNote: "높은 기초 공격력 검(천공, 늑대)과 원소 충전 부옵.",
    teamNote: "공격력 버프와 힐. 불 공명까지 열어 주는 자리가 많습니다.",
  }),
  10000047: dps({
    id: 10000047,
    role: "서포터",
    scaling: "em",
    sands: ["em"],
    goblet: ["em"],
    circlet: ["em"],
    sets: [four(["청록색", "viridescent", "venerer"])],
    setNote: "청록 4셋.",
    substats: "원소 마스터리 → 원소 충전",
    erMin: 160,
    erNote: "원소폭발을 매 로테에 쓰려면 160~180%.",
    talentFocus: "burst",
    talentNote: "원소폭발의 피해 보너스. 원소전투 레벨은 확산 피해에 영향이 없습니다.",
    weaponNote: "원소 마스터리 검(철봉, 반딧불).",
    teamNote: "확산을 넣고 원소 저항을 깎습니다. 메인 딜러의 원소를 흡수하게 원소폭발 순서를 맞춥니다.",
  }),
  10000073: dps({
    id: 10000073,
    role: "서포터",
    scaling: "em",
    sands: ["em"],
    goblet: ["em", "dendro"],
    circlet: ["em", "cr", "cd"],
    sets: [four(["숲의 기억", "deepwood"]), four(["도금", "gilded"])],
    setNote: "파티에 숲의 기억 4셋이 없으면 나히다가 착용. 있으면 도금 4셋.",
    substats: "원소 마스터리 → 치명타(필드 딜을 볼 때)",
    erMin: 120,
    erNote: "원소폭발은 40이라 120~140%면 충분합니다.",
    talentFocus: "skill",
    talentNote: "원소전투가 본체. 원소폭발은 그다음.",
    weaponNote: "원소 마스터리 법구.",
    teamNote: "풀 부착과 원소 마스터리 버프. 개화·만개·발화 파티의 중심.",
  }),
  10000065: dps({
    id: 10000065,
    role: "서포터",
    scaling: "em",
    sands: ["em"],
    goblet: ["em"],
    circlet: ["em"],
    sets: [four(["잃어버린 낙원", "paradise", "flower of paradise"]), four(["도금", "gilded"]), four(["꽃깃", "flower"])],
    setNote: "만개(하이퍼블룸)면 원소 마스터리 4셋.",
    substats: "원소 마스터리. 치유만 볼 때는 생명력.",
    erMin: 110,
    erNote: "원소폭발에 의존하지 않아도 됩니다.",
    talentFocus: "skill",
    talentNote: "원소전투 레벨은 치유량. 만개 피해는 레벨보다 원소 마스터리입니다.",
    weaponNote: "철봉, 또는 원소 마스터리 검.",
    teamNote: "나히다·행추와 만개. 치유와 번개 부착을 같이 합니다.",
  }),
  10000030: dps({
    id: 10000030,
    role: "실더",
    scaling: "hp",
    sands: ["hp_"],
    goblet: ["hp_", "geo"],
    circlet: ["hp_", "cr", "cd"],
    sets: [four(["천암", "tenacity", "millelith"]), two(["천암", "tenacity"]), two(["옛 왕실", "noblesse"])],
    setNote: "천암 4셋으로 보호막과 공격력 버프.",
    substats: "생명력% → 원소 충전",
    erMin: 130,
    erNote: "원소폭발을 자주 깔려면 140% 전후.",
    talentFocus: "skill",
    talentNote: "원소전투가 보호막. 운석을 쓸 거면 원소폭발도.",
    weaponNote: "생명력 창(호마, 흑술창, 파보).",
    teamNote: "보호막으로 경직을 막고, 바위 공명이나 저항 감소를 열어 줍니다.",
  }),
  10000054: dps({
    id: 10000054,
    role: "힐러",
    scaling: "heal",
    sands: ["hp_", "er"],
    goblet: ["hp_", "hydro"],
    circlet: ["heal", "hp_"],
    sets: [four(["바다에 물든", "ocean", "hued"]), four(["천암", "tenacity"]), four(["사랑받는 소녀", "maiden"])],
    setNote: "필드 딜이면 해염 4셋, 힐만이면 천암이나 소녀.",
    substats: "생명력% → 원소 충전",
    erMin: 160,
    erNote: "원소폭발을 힐 로테에 맞추려면 160~180%.",
    talentFocus: "skill",
    talentNote: "원소전투가 치유. 원소폭발은 필드 딜을 볼 때.",
    weaponNote: "용의 포효는 치명타를 버리므로, 생명력·충전 법구가 맞습니다. 코코미는 치명타 확률이 -100%입니다.",
    teamNote: "힐러. 원소폭발 중에는 일반 공격이 물 피해가 됩니다.",
  }),
  10000087: dps({
    id: 10000087,
    role: "메인 딜러",
    scaling: "hp",
    sands: ["hp_"],
    goblet: ["hydro", "hp_"],
    circlet: CRIT,
    sets: [four(["그림자 사냥", "marechaussee", "hunter"]), four(["황금 극단", "golden troupe"])],
    setNote: "그림자 사냥꾼 4셋.",
    substats: "생명력% → 치명타 피해. 세트 때문에 치명타 확률은 64%를 넘기지 않아도 됩니다.",
    erMin: 120,
    erNote: "원소폭발은 자주 안 써도 됩니다. 120% 전후.",
    talentFocus: "normal",
    talentNote: "평타를 먼저.",
    weaponNote: "생명력·치명타 법구.",
    teamNote: "푸리나, 또는 실드·힐과 함께 평타를 넣는 물 메인 딜러.",
  }),
  10000089: dps({
    id: 10000089,
    role: "서포터",
    scaling: "hp",
    sands: ["hp_", "er"],
    goblet: ["hp_", "hydro"],
    circlet: CRIT.concat(["hp_"]) as StatKey[],
    sets: [four(["황금 극단", "golden troupe"])],
    setNote: "황금 극단 4셋.",
    substats: "원소 충전 → 생명력% → 치명타",
    erMin: 170,
    erNote: "원소폭발 버프를 유지하려면 160~200%. 파보·페보니가 있으면 낮춰도 됩니다.",
    talentFocus: "burst",
    talentNote: "원소폭발이 피해 버프. 원소전투는 소환수의 피해.",
    weaponNote: "원소 충전 검.",
    teamNote: "생명력을 오가게 하는 힐러(진, 백출, 샤를로트, 시그윈)와 같이 씁니다.",
  }),
  10000096: dps({
    id: 10000096,
    role: "메인 딜러",
    sands: ["atk_", "em"],
    goblet: ["pyro"],
    circlet: CRIT,
    sets: [four(["조화", "fragment", "harmonic"]), four(["검투사", "gladiator"]), four(["시메나", "shimenawa"])],
    setNote: "조화의 그림자 4셋, 또는 공격력 2+2.",
    substats: "치명타 → 공격력% → 원소 마스터리",
    erMin: 120,
    erNote: "원소폭발은 생명력 회복용이라 120%면 됩니다.",
    talentFocus: "normal",
    talentNote: "평타를 먼저 올립니다.",
    weaponNote: "공격력·치명타 창.",
    teamNote: "증발·과부하. 행추·야란·체브르즈와 맞습니다. 힐에 기대지 않는 편입니다.",
  }),
  10000078: dps({
    id: 10000078,
    role: "메인 딜러",
    sands: ["em", "atk_"],
    goblet: ["dendro", "em"],
    circlet: CRIT,
    sets: [four(["도금", "gilded"]), four(["숲의 기억", "deepwood"])],
    setNote: "도금 4셋. 숲 기억은 파티원이 착용.",
    substats: "치명타 → 원소 마스터리 → 원소 충전",
    erMin: 130,
    erNote: "원소폭발로 거울을 이으려면 130~140%.",
    talentFocus: "skill",
    talentNote: "원소전투와 원소폭발을 같이.",
    weaponNote: "원소 마스터리·치명타 검.",
    teamNote: "번개(피슬, 야에, 시노부)와 풀 저항 감소가 있는 신속 파티.",
  }),
  10000002: dps({
    id: 10000002,
    role: "메인 딜러",
    sands: ["atk_"],
    goblet: ["cryo"],
    circlet: ["cd", "cr"],
    sets: [four(["얼음바람", "blizzard", "strayer"])],
    setNote: "얼음바람 4셋. 빙결이 붙으면 치명타 확률은 45% 전후여도 됩니다.",
    substats: "치명타 피해 → 공격력% → 원소 충전",
    erMin: 130,
    erNote: "원소폭발을 로테마다 쓰려면 130~140%.",
    talentFocus: "burst",
    talentNote: "원소폭발, 그다음 평타.",
    weaponNote: "공격력·치명타 피해 검(안개, 참봉 검).",
    teamNote: "빙결. 코코미·모나·신학·카즈하.",
  }),
  10000037: dps({
    id: 10000037,
    role: "메인 딜러",
    sands: ["atk_", "em"],
    goblet: ["cryo"],
    circlet: CRIT,
    sets: [four(["유랑", "방랑", "wanderer", "troupe"]), four(["얼음바람", "blizzard"]), four(["시메나", "shimenawa"])],
    setNote: "용해면 방랑자 4셋 또는 시메나와. 빙결이면 얼음바람.",
    substats: "치명타 → 공격력% → 원소 마스터리",
    erMin: 120,
    erNote: "강공격 위주면 원소 충전 부담이 적습니다.",
    talentFocus: "normal",
    talentNote: "평타를 먼저.",
    weaponNote: "공격력·치명타 활.",
    teamNote: "용해(향릉·베넷) 또는 빙결.",
  }),
  10000026: dps({
    id: 10000026,
    role: "메인 딜러",
    sands: ["atk_"],
    goblet: ["anemo"],
    circlet: CRIT,
    sets: [four(["추억의 시메나", "shimenawa", "시메나"]), four(["검투사", "gladiator"]), two(["청록색", "viridescent"])],
    setNote: "공격력 2셋 + 바람 피해 2셋, 또는 시메나와 4셋.",
    substats: "치명타 → 공격력% → 원소 충전",
    erMin: 120,
    erNote: "원소폭발 유지에 120~140%.",
    talentFocus: "burst",
    talentNote: "원소폭발 중 평타가 본체라 원소폭발과 평타를 같이.",
    weaponNote: "공격력·치명타 창.",
    teamNote: "파루잔, 베넷, 실드. 낙하 공격 파티.",
  }),
  10000057: dps({
    id: 10000057,
    role: "메인 딜러",
    scaling: "def",
    sands: ["def_"],
    goblet: ["geo", "def_"],
    circlet: CRIT,
    sets: [four(["껍데기", "풍요로운 꿈", "husk", "opulent"])],
    setNote: "풍요로운 꿈의 껍데기 4셋.",
    substats: "치명타 → 방어력% → 원소 충전",
    erMin: 130,
    erNote: "원소폭발 유지에 120~140%.",
    talentFocus: "normal",
    talentNote: "평타를 먼저, 원소폭발은 그다음.",
    weaponNote: "방어력·치명타 양손검(늑대 바위, 이토 전용).",
    teamNote: "고로, 종려 또는 알베도. 바위 공명.",
  }),
  10000034: dps({
    id: 10000034,
    role: "메인 딜러",
    scaling: "def",
    sands: ["def_", "er"],
    goblet: ["geo", "def_"],
    circlet: CRIT,
    sets: [four(["껍데기", "풍요로운 꿈", "husk", "opulent"]), four(["검투사", "gladiator"])],
    setNote: "풍요로운 꿈의 껍데기 4셋 또는 검투사 4셋.",
    substats: "원소 충전 → 방어력% → 치명타",
    erMin: 140,
    erNote: "원소폭발을 유지해야 방어력이 공격력으로 바뀝니다.",
    talentFocus: "burst",
    talentNote: "원소폭발을 먼저.",
    weaponNote: "방어력·충전 양손검(백영, 이토 무기).",
    teamNote: "바위 공명과 배터리(고로, 응광).",
  }),
  10000091: dps({
    id: 10000091,
    role: "메인 딜러",
    sands: ["atk_"],
    goblet: ["geo"],
    circlet: CRIT,
    sets: [four(["메아리숲", "야화", "nighttime", "whispers"]), four(["검투사", "gladiator"]), two(["창백", "pale flame"]), two(["피에 물든", "bloodstained"])],
    setNote: "메아리숲의 야화 4셋, 또는 공격력 2+2.",
    substats: "치명타 → 공격력% → 원소 충전",
    erMin: 120,
    erNote: "원소폭발은 결정 생성용. 130% 전후면 됩니다.",
    talentFocus: "skill",
    talentNote: "원소전투를 먼저.",
    weaponNote: "공격력·치명타 양손검.",
    teamNote: "결정 반응을 만들 다른 원소 둘(행추, 베넷, 향릉, 푸리나).",
  }),
  10000106: dps({
    id: 10000106,
    role: "메인 딜러",
    sands: ["atk_", "em"],
    goblet: ["pyro"],
    circlet: CRIT,
    sets: [four(["흑요석", "obsidian", "codex"]), four(["검투사", "gladiator"])],
    setNote: "흑요석 비전 4셋.",
    substats: "치명타 피해 → 공격력% → 원소 마스터리. 세트·특성으로 치명타 확률이 찹니다.",
    erMin: 120,
    erNote: "싸움의 불꽃을 유지할 정도면 됩니다.",
    talentFocus: "burst",
    talentNote: "원소폭발 후 평타. 둘 다 올립니다.",
    weaponNote: "공격력·치명타 양손검.",
    teamNote: "시틀라리, 벤넷, 실로닌 같은 나츠 서포터.",
  }),
  10000031: dps({
    id: 10000031,
    role: "서브 딜러",
    sands: ["atk_"],
    goblet: ["electro", "atk_"],
    circlet: CRIT,
    sets: [four(["황금 극단", "golden troupe"])],
    setNote: "황금 극단 4셋.",
    substats: "치명타 → 공격력%",
    erMin: 120,
    erNote: "오즈만 깔면 충전 부담이 작습니다.",
    talentFocus: "skill",
    talentNote: "원소전투만 올려도 됩니다.",
    weaponNote: "공격력·치명타 활.",
    teamNote: "신속·감전·과부하의 번개 부착.",
  }),
  10000098: dps({
    id: 10000098,
    role: "메인 딜러",
    sands: ["atk_"],
    goblet: ["electro"],
    circlet: CRIT,
    sets: [four(["조화", "fragment", "harmonic"]), four(["황금 극단", "golden troupe"])],
    setNote: "조화의 그림자 4셋.",
    substats: "치명타 → 공격력% → 원소 충전",
    erMin: 130,
    erNote: "원소폭발로 생명력 인장을 회수하려면 120~140%.",
    talentFocus: "skill",
    talentNote: "원소전투와 원소폭발을 같이.",
    weaponNote: "공격력·치명타 검.",
    teamNote: "과부하(체브르즈) 또는 신속(나히다).",
  }),
  10000103: dps({
    id: 10000103,
    role: "서포터",
    scaling: "def",
    sands: ["def_", "er"],
    goblet: ["def_", "geo"],
    circlet: ["def_", "heal", "cr"],
    sets: [four(["잿더미", "scroll", "cinder", "영웅"])],
    setNote: "잿더미 성 영웅의 두루마리 4셋.",
    substats: "방어력% → 원소 충전",
    erMin: 140,
    erNote: "원소폭발 샘플을 유지하려면 130~160%.",
    talentFocus: "skill",
    talentNote: "원소전투가 저항 감소. 원소폭발은 힐과 샘플.",
    weaponNote: "방어력 검.",
    teamNote: "나츠 파티의 저항 감소와 힐. 원소 샘플을 파티 원소에 맞춥니다.",
  }),
  10000123: dps({
    id: 10000123,
    role: "서브 딜러",
    sands: ["atk_", "em", "er"],
    goblet: ["pyro", "atk_"],
    circlet: CRIT,
    sets: [four(["바람이 시작되는 날", "rising"]), four(["절연", "emblem"]), four(["옛 왕실", "noblesse"])],
    setNote: "개인 피해는 바람이 시작되는 날 4셋. 파티 공격력이 필요하면 옛 왕실, 충전이 부족하면 절연.",
    substats: "치명타 → 공격력% → 원소 충전 → 원소 마스터리",
    erMin: 130,
    erNote: "원소폭발을 매 로테에 쓰려면 120~140%. 혼자 원소 입자를 못 받으면 더 필요합니다.",
    talentFocus: "burst",
    talentNote: "원소폭발을 먼저. 원소전투는 그다음이고, 평타는 올리지 않아도 됩니다.",
    weaponNote: "공격력·치명타 검. 충전이 부족하면 페보니우스나 제례검.",
    teamNote: "증발·융해 파티의 불 서브 딜러. 베넷, 행추, 마비카와 자주 붙습니다.",
  }),
  10000140: dps({
    id: 10000140,
    role: "힐러",
    scaling: "heal",
    sands: ["hp_", "er"],
    goblet: ["hp_"],
    circlet: ["heal", "hp_"],
    sets: [four(["천암", "tenacity"]), four(["바다에 물든", "ocean", "hued"]), four(["사랑받는 소녀", "maiden"])],
    setNote: "견고한 천암 4셋이면 치유와 함께 파티 공격력을 줍니다. 치유만 보면 바다에 물든 거대 조개.",
    substats: "생명력% → 원소 충전",
    erMin: 160,
    erNote: "원소폭발을 돌리려면 150~180%.",
    talentFocus: "skill",
    talentNote: "원소전투가 치유와 내성 감소의 본체입니다. 원소폭발은 그다음.",
    weaponNote: "드래곤 슬레이어의 영웅담이 파티 공격력에 좋고, 없으면 생명력 법구.",
    teamNote: "물·얼음 내성을 깎고 치유합니다. 별 확산 파티의 힐러 자리.",
  }),
};
